### ISSUE TITLE
Add ability to name the Kinesis stream associated with a model

### ISSUE THREAD

**Issue by gkallenberg** [NYPL/php-microservice-starter#1]

**Comment by gkallenberg** [comment]
Looks like my pull request missed the mark on the update traits. DBUpdateTrait and CacheUpdateTrait classes also need $this->getObjectName() replaced with $this->getStreamName() for their respective publishMessage calls a la the way the *CreateTrait classes do. Sorry to catch this late.

**Comment by kfriedman** [comment]
I'm pretty show this has been resolved, right? @gkallenberg can you close?
